export const CodeOfConductTags = [
  '#Java',
  '#Concurrency',
  '#IoT',
  '#Cloud',
  '#Docker',
  '#CD',
  '#Mesos',
  '#TDD',
  '#JVM langs',
  '#Scalability',
  '#SQA',
  '#Microservices',
  '#noSQL',
  '#CI',
  '#Functional Programming',
  '#Actors',
  '#Mobile',
  '#DevOps',
  '#DDD',
  '#Integration',
  '#Architecture',
  '#Testing',
  '#MArathon',
  '#Kubernetes',
];
