export const speakersData = [
  {
    title: 'ANTÓN RODRÍGUEZ',
    subtitle: 'Principal Software engineer',
    speakerImage: 1,
    text: 'Kafka y Pulsar: una comparación gentil',
  },
  {
    title: 'MALA GUPTA',
    subtitle: 'Developer Advocate @JetBrains, Published Author',
    speakerImage: 1,
    text: 'IntelliJ IDEA and Keeping Pace with the New Java Language Features',
  },
  {
    title: 'DAVID GÓMEZ G.',
    subtitle: 'Developer Advocate',
    speakerImage: 1,
    text: 'Construyendo aplicaciones monolíticas que puedan escalar a micro servicios',
  },
  {
    title: 'AUREA MUNOZ',
    subtitle: 'Software Engineer',
    speakerImage: 1,
    text: 'Despliega en Kubernetes usando Dekorate',
  },
  {
    title: 'ANA-MARIA MIHALCEANU',
    subtitle: 'Architect',
    speakerImage: 1,
    text: 'Techniques for maintainable Quarkus Applications',
  },
  {
    title: 'THOMAS VITALE',
    subtitle: 'Senior Software Engineer',
    speakerImage: 1,
    text: 'Event-driven and serverless with Spring Cloud and Spring Native',
  },
  {
    title: 'ANTÓN RODRÍGUEZ',
    subtitle: 'Principal Software engineer',
    speakerImage: 1,
    text: 'Kafka y Pulsar: una comparación gentil',
  },
  {
    title: 'ANTÓN RODRÍGUEZ',
    subtitle: 'Principal Software engineer',
    speakerImage: 1,
    text: 'Kafka y Pulsar: una comparación gentil',
  },
  {
    title: 'MALA GUPTA',
    subtitle: 'Developer Advocate @JetBrains, Published Author',
    speakerImage: 1,
    text: 'IntelliJ IDEA and Keeping Pace with the New Java Language Features',
  },
  {
    title: 'DAVID GÓMEZ G.',
    subtitle: 'Developer Advocate',
    speakerImage: 1,
    text: 'Construyendo aplicaciones monolíticas que puedan escalar a micro servicios',
  },
  {
    title: 'AUREA MUNOZ',
    subtitle: 'Software Engineer',
    speakerImage: 1,
    text: 'Despliega en Kubernetes usando Dekorate',
  },
  {
    title: 'ANA-MARIA MIHALCEANU',
    subtitle: 'Architect',
    speakerImage: 1,
    text: 'Techniques for maintainable Quarkus Applications',
  },
  {
    title: 'THOMAS VITALE',
    subtitle: 'Senior Software Engineer',
    speakerImage: 1,
    text: 'Event-driven and serverless with Spring Cloud and Spring Native',
  },
  {
    title: 'ANTÓN RODRÍGUEZ',
    subtitle: 'Principal Software engineer',
    speakerImage: 1,
    text: 'Kafka y Pulsar: una comparación gentil',
  },
  {
    title: 'ANTÓN RODRÍGUEZ',
    subtitle: 'Principal Software engineer',
    speakerImage: 1,
    text: 'Kafka y Pulsar: una comparación gentil',
  },
  {
    title: 'MALA GUPTA',
    subtitle: 'Developer Advocate @JetBrains, Published Author',
    speakerImage: 1,
    text: 'IntelliJ IDEA and Keeping Pace with the New Java Language Features',
  },
  {
    title: 'DAVID GÓMEZ G.',
    subtitle: 'Developer Advocate',
    speakerImage: 1,
    text: 'Construyendo aplicaciones monolíticas que puedan escalar a micro servicios',
  },
  {
    title: 'AUREA MUNOZ',
    subtitle: 'Software Engineer',
    speakerImage: 1,
    text: 'Despliega en Kubernetes usando Dekorate',
  },
  {
    title: 'ANA-MARIA MIHALCEANU',
    subtitle: 'Architect',
    speakerImage: 1,
    text: 'Techniques for maintainable Quarkus Applications',
  },
  {
    title: 'THOMAS VITALE',
    subtitle: 'Senior Software Engineer',
    speakerImage: 1,
    text: 'Event-driven and serverless with Spring Cloud and Spring Native',
  },
  {
    title: 'ANTÓN RODRÍGUEZ',
    subtitle: 'Principal Software engineer',
    speakerImage: 1,
    text: 'Kafka y Pulsar: una comparación gentil',
  },
];
